RayelinkWeixin.Web/Models/MyComment.cs
using RayelinkWeixin.Const.Config;
using System;
using System.Security.Principal;
using System.Web;
using System.Web.Security;

namespace RayelinkWeixin.Web.Models
{ /// <summary>
    /// 
    /// </summary>
    [Serializable]
    public class MyComment
    {
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string DepName { get; set; }
        public string TitleName { get; set; }
        public string DoctorImage { get; set; }
        public string DoctorComment { get; set; }
        public int DoctorStar { get; set; }
        public string DoctorReplyContent { get; set; }
        public int HospId { get; set; }
        public string HospName { get; set; }
        public string HospImage { get; set; }
        public string HospComment { get; set; }
        public int HospStar { get; set; }
        public string AddTimeString { get; set; }
        public int VisitId { get; set; }
        public bool HasReplyComment { get; set; }
    }
}

RayelinkWeixin.Web/Controllers/DoctorController.cs
/*----------------------------------------------------------------
// Copyright (C) 2016苏州盈天地资讯科技公司
// 版权所有。
// 文   件   名：DoctorController
// 文件功能描述：
//
// 
// 创 建 人：haiqing
// 创建日期：2016-01-21
//
// 修 改 人：
// 修改描述：
//
// 修改标识：
//----------------------------------------------------------------*/

using Newtonsoft.Json;
using RayelinkWeixin.Common.Utilites;
using RayelinkWeixin.Const.Config;
using RayelinkWeixin.Const.Const;
using RayelinkWeixin.Model;
using RayelinkWeixin.Web.Filters;
using RayelinkWeixin.Web.Models;
using Senparc.Weixin.MP.Containers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using RayelinkWeixin.Web.Controllers;

namespace RayelinkWeixin.Web.Areas.ReVisit.Controllers
{
    [AllowAnonymous]
    public class DoctorController : BaseController
    {
        /// <summary>
        /// 进入专家列表页面
        /// </summary>
        /// <returns></returns>
        [WeixinSpeficAuthorize]
        public ActionResult DoctorList()
        {

            var url = Request.Url.ToString().Split('#')[0];
            ViewBag.JsSDKModel = JsSDKModel.GetJsSDKModel(url);
            // 科室  职称列表（带缓存）
            var objDept = CacheHelper.GetCache(KeyConst.CacheAllDept);
            var objTitle = CacheHelper.GetCache(KeyConst.CacheAllTitle);
            var listDepartment = new List<SelectItemModel>();
            var listTitle = new List<SelectItemModel>();
            CRSService.CRS_ServiceSoapClient client = new CRSService.CRS_ServiceSoapClient();
            // 判断缓存是否有
            if (objDept != null)
            {
                listDepartment = objDept as List<SelectItemModel>;
            }
            else
            {
                listDepartment.Add(new SelectItemModel()
                {
                    id = "",
                    name = "全部"
                });

                var returnModel = client.getDeptList();
                var deptJson = returnModel.Data.ToString();
                var deptList = JsonConvert.DeserializeObject<List<SelectItemModel>>(deptJson).OrderBy(p => p.name).ToList();
                foreach (SelectItemModel obj in deptList)
                {
                    obj.name = obj.name.Length > 8 ? obj.name.Substring(0, 8) + "..." : obj.name;
                }
                listDepartment.AddRange(deptList.ToArray());
                if (listDepartment.Count > 0)
                {
                    CacheHelper.SetCache(KeyConst.CacheAllDept, listDepartment);
                }
            }
            // 判断缓存是否有
            if (objTitle != null)
            {
                listTitle = objTitle as List<SelectItemModel>;
            }
            else
            {
                listTitle.Add(new SelectItemModel()
                {
                    id = "",
                    name = "全部"
                });
                var returnModel1 = client.getTitleList();
                var titleJson = returnModel1.Data.ToString();
                var titleList = JsonConvert.DeserializeObject<List<SelectItemModel>>(titleJson);
                listTitle.AddRange(titleList.ToArray());
                if (listTitle.Count > 0)
                {
                    CacheHelper.SetCache(KeyConst.CacheAllTitle, listTitle);
                }
            }
            ViewBag.Department = listDepartment;
            ViewBag.Title = listTitle;
            return View();
        }

        /// <summary>
        /// 获取专家列表数据
        /// </summary>
        /// <param name="deptid">部门</param>
        /// <param name="titleid">职称</param>
        /// <param name="keyword">关键字</param>
        /// <param name="currentIndex">当前页</param>
        /// <param name="page">页数</param>
        /// <returns></returns>
        public ActionResult GetDoctorList(int? deptid, int? titleid, string keyword, int currentIndex, int page = 10)
        {
            CRSService.CRS_ServiceSoapClient client = new CRSService.CRS_ServiceSoapClient();
            var returnModel = client.getDoctorList(deptid, titleid, keyword,"","1,2,3","", currentIndex, page);
            var doctorListJson = "";
            if (returnModel.Data != null)
            {
                doctorListJson = returnModel.Data.ToString();
            }
            if (doctorListJson == "")
            {
                doctorListJson = "[]"; //防止前台jquery ajax报parseerror 错误
            }
            return Content(doctorListJson);


        }

        /// <summary>
        /// 搜索页
        /// </summary>
        /// <returns></returns>
        [WeixinSpeficAuthorize]
        public ActionResult DoctorSearch()
        {
            var url = Request.Url.ToString().Split('#')[0];
            ViewBag.JsSDKModel = JsSDKModel.GetJsSDKModel(url);
            return View();
        }

        /// <summary>
        /// 搜索空白页
        /// </summary>
        /// <param name="searchText"></param>
        /// <returns></returns>
        [WeixinSpeficAuthorize]
        public ActionResult DoctorSearchNull(string searchText)
        {
            var url = Request.Url.ToString().Split('#')[0];
            ViewBag.JsSDKModel = JsSDKModel.GetJsSDKModel(url);
            ViewBag.searchText = searchText;
            return View();
        }

        /// <summary>
        /// 医生详情页
        /// </summary>
        /// <param name="id">医生id</param>
        /// <param name="date">日期</param>
        /// <param name="isPrize">定位送心意</param>
        /// <returns></returns>
        [WeixinSpeficAuthorize]
        public ActionResult DoctorSub(int id, string date = "", int isPrize =0)
        {
            var url = Request.Url.ToString().Split('#')[0];
            ViewBag.JsSDKModel = JsSDKModel.GetJsSDKModel(url);
            ViewBag.isPrize = isPrize;
            CRSService.CRS_ServiceSoapClient client = new CRSService.CRS_ServiceSoapClient();
            DoctorModel doctorModel = new DoctorModel();
            var returnModel5 = client.getDoctor(id);
            // 获得医生详细数据
            var doctorJson = "";
            if (returnModel5.Data != null)
            {
                doctorJson = returnModel5.Data.ToString();
                if (doctorJson != "")
                {
                    doctorModel = JsonConvert.DeserializeObject<DoctorModel>(doctorJson);
                }
            }


            if (User.Identity.IsAuthenticated)
            {
                var user = AuthorizeUser.GetAuthorizeUser(User.Identity.Name);
                if (user != null)
                {
                    // 是否关注医生
                    var returnModel = client.isAttention(user.pid, id);
                    var attentionJson = "0";
                    if (returnModel.Data != null)
                    {
                        attentionJson = returnModel.Data.ToString();
                    }
                    if ("0".Equals(attentionJson))
                    {
                        doctorModel.isFocus = false;
                    }
                    else
                    {
                        doctorModel.isFocus = true;
                    }
                    doctorModel.isLogin = true;
                    doctorModel.userName = user.username;
                }
            }
            else
            {
                doctorModel.isFocus = false;
                doctorModel.isLogin = false;
                doctorModel.userName = AuthorizeUser.nickname();
            }
            #region 医生信息 应该从接口获取

            var pid = 0;
            if (User.Identity.IsAuthenticated)
            {
                var user = AuthorizeUser.GetAuthorizeUser(User.Identity.Name);
                if (user != null)
                {
                    pid = user.pid;
                }
            }

            #region 我的咨询
            var returnModel6 = client.GetLatestUserConsultations(id, pid);
            var latestUserMessageJson = "";
            if (returnModel6.Data != null)
            {
                latestUserMessageJson = returnModel6.Data.ToString();
            }
            doctorModel.currentLatestConsult = new OnlineConsultModel();
            if (latestUserMessageJson != "")
            {
                var latestUserMessageModel = JsonConvert.DeserializeObject<OnlineConsultModel>(latestUserMessageJson);

                if (latestUserMessageModel != null)
                {
                    doctorModel.currentLatestConsult = latestUserMessageModel;
                    doctorModel.currentLatestConsult.CreateTime = Convert.ToDateTime(doctorModel.currentLatestConsult.CreateTime).ToString("yyyy.MM.dd");
                    doctorModel.currentLatestConsult.Content = doctorModel.currentLatestConsult.Content;
                }
            }
            
            // 其他咨询
            var returnModel7 = client.GetTopUserConsultations(id, pid, 4);
            var userMessageListJson = returnModel7.Data.ToString();
            var userMessageListModel = JsonConvert.DeserializeObject<List<OnlineConsultModel>>(userMessageListJson);
            if (userMessageListModel != null)
            {
                foreach (var OnlineConsultModel in userMessageListModel)
                {
                    OnlineConsultModel.CreateTime = Convert.ToDateTime(OnlineConsultModel.CreateTime).ToString("yyyy.MM.dd");
                    OnlineConsultModel.UserName = OnlineConsultModel.UserName.Substring(0, 1) + "**";
                    OnlineConsultModel.Content = OnlineConsultModel.Content;
                }
            }

            doctorModel.listConsult = new List<OnlineConsultModel>();
            if (userMessageListModel != null)
            {
                doctorModel.listConsult.AddRange(userMessageListModel.ToArray());
            }
            #endregion

            #region 评论
            doctorModel.listUserComments = new List<UserCommentModel>();
            var returnModel2 = client.getCommentList(id, null, pid, 1, 5);

RayelinkWeixin.Web/Controllers/MessageController.cs
/*----------------------------------------------------------------
// Copyright (C) 2016苏州盈天地资讯科技公司
// 版权所有。
// 文   件   名：MessageController
// 文件功能描述：
//
// 
// 创 建 人：haiqing
// 创建日期：2016-01-19
//
// 修 改 人：
// 修改描述：
//
// 修改标识：
//----------------------------------------------------------------*/

using Newtonsoft.Json;
using RayelinkWeixin.Common.Utilites;
using RayelinkWeixin.Model;
using System.Web.Mvc;

namespace RayelinkWeixin.Web.Controllers
{
    [AllowAnonymous]
    public class MessageController : BaseController
    {
        #region 发送手机获取验证码
        /// <summary>
        /// 发送手机获取验证码
        /// </summary>
        /// <param name="mobile">接收手机号</param>
        /// <param name="type">区分这次验证码的活动标识</param>
        /// <returns></returns>
        public JsonResult SendMessageValidCode(string mobile, string type = "mobile")
        {
            if (!validateUserFotCapcha(mobile, HttpContext.Request.UserHostAddress))
            {
                LogHelper.Info("/***********拒绝短信**********/ \r\n 手机号:" + mobile + "\r\n SessionID:" + Session.SessionID + "\r\n  IP:" + HttpContext.Request.UserHostAddress + "\r\n/***********End**********/");
                return Json(new { success = false, message = "您的请求过于频繁，请改日再来。" });
            }

            string cacheKey = string.Format(ValidCodeCacheKey, mobile, type);
            SMS_Service.WebServiceClient client = new SMS_Service.WebServiceClient();
            var code = CookieHelper.GetValueByCookieskey(Request, cacheKey);  //先从缓存里面取出没有过期的验证码
            if (string.IsNullOrWhiteSpace(code))
            {
                code = RadomHelper.GetRandomString(6);
            }
            string content = "验证码：" + code + "，请在10分钟内完成验证。如非本人操作，请忽略。";
            var jsonStr = client.sendMsg(mobile, content, "BMY", "CMCC_BMY");
            var obj = JsonConvert.DeserializeObject<CRMMessageResult>(jsonStr);
            var message = "验证码已发送，请注意查收";
            if (obj.success)
            {
                CookieHelper.AddCookies(Response, cacheKey, code, 10);
            }
            else
            {
                message = obj.info;
            }
            Session[cacheKey] = jsonStr;
            return Json(new { success = obj.success, message = message });
        }

        /// <summary>
        /// 验证验证码是否正确
        /// </summary>
        /// <param name="mobile">接收手机号</param>
        /// <param name="code">需要校验的验证码</param>
        /// <param name="type">区分这次验证码的活动标识</param>
        /// <param name="expendCode">是否消耗掉这次的验证码(1:是，从缓存里面清理掉)</param>
        /// <returns></returns>
        public JsonResult ValidMessageCode(string mobile, string code, string type = "mobile", byte expendCode = 0)
        {
            Common.Share.ReturnMessage rm = ValidCode(mobile, code, type, expendCode.Equals(1));
            return Json(new { success = rm.IsSuccess, message = rm.Text });
        } 
        #endregion

    }
}

RayelinkWeixin.Web/Views/User/AddUser.cshtml
@{
    Layout = null;
    var type = ViewBag.type;
    var jsSDKModel = ViewBag.JsSDKModel as RayelinkWeixin.Web.Models.JsSDKModel;
}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>添加就诊人</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta http-equiv="cleartype" content="on">
    <meta name="format-detection" content="telephone=no" />
    <link rel="stylesheet" href="../styles/base.css?v=2">
    <link rel="stylesheet" href="../styles/order_page.css">
    <link rel="stylesheet" href="../styles/edit_user.css">
    <script src="../vendor/jquery-2.1.0.min.js"></script>
    <script src="../scripts/base.js?v=2"></script>
    <script src="../scripts/add_user.js"></script>
    <script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
    <script>
        wx.config({
            debug: false,
            appId: '@jsSDKModel.appId',
            timestamp: '@jsSDKModel.timestamp',
            nonceStr: '@jsSDKModel.nonceStr',
            signature: '@jsSDKModel.signature',
            jsApiList: ['hideAllNonBaseMenuItem']
        });
        wx.ready(function () {
            wx.hideAllNonBaseMenuItem();
        });
    </script>
    <style>
        .submit.custom_style_edit {
            text-align: center;
            /*padding-left: 40px;*/
            display: block;
            height: 20px;
        }

        .checkBtn {
            display: inline-block;
            width: 30px;
            height: 28px;
            background: url(../images/user_center/checkOff.png) no-repeat;
            background-size: 90% auto;
            position: absolute;
            top: 50%;
            right: 30px;
            transform: translateY(-50%);
            -webkit-transform: translateY(-50%);
            -ms-transform: translateY(-50%);
            -moz-transform: translateY(-50%);
            -o-transform: translateY(-50%);
        }

            .checkBtn.checkOn {
                background: url(../images/user_center/checkOn.png) no-repeat;
                background-size: 90% auto;
            }

        .submit.custom_style_edit {
            height: 40px;
        }
		@@media (max-width:320px){
			#code{
               width:110px;
           }
		   #name,#phone,#id{
				width:170px;
			}
        }
		@@media only screen and (min-width: 330px) and  (max-width:414px){
			#code{
               width:140px;
           }
		   #name,#phone,#id{
				width:210px;
			}
        }
		
		@@media only screen and (min-width: 414px) and  (max-width:640px){
			#code{
               width:140px;
           }
		   #name,#phone,#id{
				width:220px;
			}
        }
    </style>
</head>
<body>
    <div class="wrap custom_style">
        <form action="#" id="user_form" class="custom_style_edit">
            <section class="save_section">
                <a href="javascript:;" class="save_btn">保存</a>
            </section>
            <section id="user_name" class="custom_style_edit">
                <label for="name">姓名</label>
                <input type="text" id="name" placeholder="请输入真实姓名" onkeyup="showDelete_Icon()" oninput="showDelete_Icon()">
                <i class="delete_icon custom_style" style="display:none" id="showIcon_name"></i>
                <span class="change_user hide">更换就诊人<i class="arrow_left custom_style"></i></span>

            </section>
            <section id="user_phone" class="custom_style_edit">
                <label for="phone">手机号</label>
                <input type="tel" id="phone" placeholder="请输入手机号" onkeyup="showDelete_Icon()" oninput="showDelete_Icon()">
                <i class="delete_icon custom_style" id="showIcon_phone" style="display:none"></i>
            </section>
            <section id="check_code" class="custom_style">
                <label for="code">验证码</label>
                <input type="tel" id="code" placeholder="请填写验证码" onkeyup="showDelete_Icon()" oninput="showDelete_Icon()">
                <i class="delete_icon custom_style" id="showIcon_code" style="display:none;right:85px;"></i>
                <i id="get_code" class="get_code custom_style">获取验证码</i>
            </section>
            <section id="user_id" class="custom_style_edit">
                <label for="id">身份证</label>
                <input type="text" id="id" placeholder="请输入真实的身份证号" onkeyup="showDelete_Icon()" oninput="showDelete_Icon()">
                <i class="delete_icon custom_style" id="showIcon_id" style="display:none;"></i>
            </section>
        </form>
        <a href="javascript:;" class="submit custom_style_edit">设置为默认就诊人</a>
    </div>
    <input type="hidden" id="hidIsDefault" value="0" />
    <script>
        var wait = 60;
        var $GetCode = $('#get_code');
        var sendMessage = function () {
            $GetCode.on('click', function () {//点击获取验证码事件
                var $This = $(this);
                var phone = $.trim($('#phone').val());
                if (phone == '') {
                    base.caozuotishi(2, '请输入正确的手机号!');
                    return false;
                }
                var checkphone = /^1[3|4|5|7|8][0-9]\d{4,8}$/;
                if (!checkphone.test(phone)) {
                    base.caozuotishi(2, '请输入正确的手机号！');
                    return false;
                }
                $This.off('click').css('background', '#b1b1b1').html(wait + 's');//等待时间效果
                messageAnimate(wait);
                var url = '@Url.Action("SendMessageValidCode", "Message")';//发送验证码
                $.post(url, { mobile: phone }, function (data) {
                    if (data.success) {
                        base.caozuotishi(1, data.message);
                    } else {
                        base.caozuotishi(2, data.message);
                    }
                });
            });
        };
        sendMessage();
        var messageAnimate = function (wait) {
            if (wait == 0) {
                $GetCode.css('background', '#00abb0').html('获取验证码');
                wait = 60;
                sendMessage();
            } else {
                wait--;
                setTimeout(function () {
                    $GetCode.html(wait + 's');
                    messageAnimate(wait)
                }, 500);
            }
        };
        $(".submit").on('click', function () {//设置为默认就诊人
            // 1 表示默认就诊人 0表示否
            $('#hidIsDefault').val(1);
            var name = $('#name').val();
            var isDefault = $('#hidIsDefault').val();
            var phone = $('#phone').val();
            var checkphone = /^1[3|4|5|7|8][0-9]\d{4,8}$/;
            var checkname = /^[\u4E00-\u9FFF]{2,15}$/;
            setTimeout(function () {//延迟0.5秒后验证输入框
                if (name == "") {
                    base.caozuotishi(2, '请输入正确的姓名！');
                    return false;
                }
                if (!checkname.test(name)) {
                    base.caozuotishi(2, '请输入正确的姓名！');
                    return false;
                }
                if (base.is_emoji(name)) {
                    base.caozuotishi(2, '无法输入表情');
                    return false;
                }
                if (name.length > 16 || name.length < 2) {
                    base.caozuotishi(2, '请输入正确的姓名！');
                    return false;
                }
                if (!checkphone.test(phone)) {
                    base.caozuotishi(2, '请输入正确的手机号！');
                    return false;
                }
                var id = $('#id').val();
                var checkid = /^(\d{15}$|^\d{18}$|^\d{17}(\d|X|x))$/;//正则表达式
                if (!checkid.test(id)) {
                    base.caozuotishi(2, "请输入正确的身份证号！");
                    return false;
                }
                var code = $.trim($('#code').val());
                if (code == '') {
                    base.caozuotishi(2, '验证码不能为空！');
                    return false;
                }
                base.caozuotishi(1, '设置成功');
            }, 500);
        });

        $(".save_btn").on('click', function () {//保存
            // 1 表示默认就诊人 0表示否
            var isDefault = $('#hidIsDefault').val();
            var phone = $('#phone').val();
            var name = $('#name').val();
            var checkname = /^[\u4E00-\u9FFF]{2,15}$/;
            var checkphone = /^1[3|4|5|7|8][0-9]\d{4,8}$/;
            setTimeout(function () {//延迟0.5秒后验证输入框
                if (name == "") {
                    base.caozuotishi(2, '请输入正确的姓名！');
                    return false;
                }
                if (!checkname.test(name)) {
                    base.caozuotishi(2, '请输入正确的姓名！');
                    return false;
                }
                if (base.is_emoji(name)) {
                    base.caozuotishi(2, '无法输入表情');
                    return false;
                }
                if (name.length > 16 || name.length < 2) {
                    base.caozuotishi(2, '请输入正确的姓名！');
                    return false;
                }
                if (!checkphone.test(phone)) {
                    base.caozuotishi(2, '请输入正确的手机号！');
                    return false;
                }
                var code = $.trim($('#code').val());
                if (code == '') {
                    base.caozuotishi(2, '请输入正确的验证码！');
                    return false;
                }
                var id = $('#id').val();
                var checkid = /^(\d{15}$|^\d{18}$|^\d{17}(\d|X|x))$/;
                if (!checkid.test(id)) {
                    base.caozuotishi(2, "请输入正确的身份证号！");
                    return false;
                }


                var url = '@Url.Action("ValidMessageCode", "Message")';//判断验证码是否正确
                $.post(url, { mobile: phone, code: code }, function (data) {
                    if (data.success) {
                        $.post('/User/User_Add', { name: $('#name').val(), phone: phone, id: id, isDefault: isDefault, openid: $('#hidStorageOpenID').val() }, function (data) {//添加就诊人
                            if (data.success) {
                                window.location.href = "/User/ChooseUser?type=" + '@type';//成功后：跳转至我的就诊人界面
                            } else {
                                base.caozuotishi(2, '保存失败！');
                                return false;
                            }
                        });
                    } else {
                        base.caozuotishi(2, data.message);
                        return false;
                    }
                });
            }, 500);

        });

        function showDelete_Icon() {//x删除图标的显示与隐藏
            var name = $("#name").val();
            var phone = $("#phone").val();
            var id = $("#id").val();
            var code = $("#code").val();
            var namelen = name.length;
            var phonelen = phone.length;
            var idlen = id.length;
            var codelen = code.length;
            if (namelen > 0) {
                $("#showIcon_name").show();
            }
            else {
                $("#showIcon_name").hide();
            }
            if (phonelen > 0) {
                $("#showIcon_phone").show();
            }
            else {
                $("#showIcon_phone").hide();
            }
            if (idlen > 0) {
                $("#showIcon_id").show();
            }
            else {
                $("#showIcon_id").hide();
            }
            if (codelen > 0) {
                $("#showIcon_code").show();
            }
            else {
                $("#showIcon_code").hide();
            }

        }
    </script>
</body>
</html>

RayelinkWeixin.Web/Views/User/ChooseUser.cshtml
@{
    Layout = null;
    var base64Url = "";
    if (Model.url != null)
    {
        base64Url = RayelinkWeixin.Common.Utilites.Base64Helper.EncodeBase64(Model.url);
    }

    var jsSDKModel = ViewBag.JsSDKModel as RayelinkWeixin.Web.Models.JsSDKModel;
}
@model UserModel
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>我的就诊人</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta http-equiv="cleartype" content="on">
    <meta name="format-detection" content="telephone=no" />
    <link rel="stylesheet" href="../styles/base.css?v=2">
    <link rel="stylesheet" href="../styles/order_page.css">
    <link rel="stylesheet" href="../styles/choose_user.css">
    <script src="../vendor/jquery-2.1.0.min.js"></script>
    <script src="../scripts/base.js?v=1"></script>
    <script src="../vendor/jsrender.min.js"></script>
    <script src="../scripts/choose_user.js"></script>
    <script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
    <script>
        wx.config({
            debug: false,
            appId: '@jsSDKModel.appId',
            timestamp: '@jsSDKModel.timestamp',
            nonceStr: '@jsSDKModel.nonceStr',
            signature: '@jsSDKModel.signature',
            jsApiList: ['hideAllNonBaseMenuItem']
        });
        wx.ready(function () {
            wx.hideAllNonBaseMenuItem();
        });
    </script>
    <style>
        .submit.custom_style{
         position: relative;
         bottom: -20px
    }
        .wrap.custom_style{
        
            padding-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="wrap custom_style">
        <ul class="user_list"></ul>
        <a href="javascript:;" class="submit custom_style">添加就诊人</a>
    </div>
    <input type="hidden" id="hidUrl" value="@Model.url" />
    <input type="hidden" id="hidBase64Url" value="@base64Url" />
    <input type="hidden" id="hidType" value="@Model.type" />
    <script>
        $(".submit").on('click', function () {//添加就诊人
            if ($('#hidType').val() != 1) {
                window.location.href = "/User/AddUser?type=" + $('#hidType').val();
            }
            else {
                window.location.href = "/User/AddUser?type=" + $('#hidType').val() + "&hidUrl=" + $('#hidBase64Url').val();
            }
        });
        var WebAPP = (function () {
            var common = {
                openid: $('#hidStorageOpenID').val(),
                url: $('#hidUrl').val()
            };
            //加载就诊人数据
            var initChooseUserData = function () {
                $.get("../tpl/user/choose_userlist.tpl.html?v=2", function (value) {
                    var tpl = $.templates(value);
                    var $chooseUserWarp = $('.wrap').find('ul');
                    $.post('/User/GetChooseUserList', { openid: common.openid }, function (data) {//获取就诊人列表数据
                        if (data != null && data != "") {
                            var html = tpl.render(data);
                            $chooseUserWarp.empty().html(html);
                        }

                    }).done(function () {
                        $chooseUserWarp.on('click', '.user_inner', function () {
                            var $This = $(this).closest('li');
                            var id = $This.data('id');
                            if ($('#hidType').val() != 1) {
                                window.location.href = "/User/EditUser?id=" + id;//编辑就诊人
                            }
                            else {
                                window.location.href = $('#hidUrl').val() + "&userId=" + id;
                            }
                        });
                    });
                });
            };
            return { common: common, initChooseUserData: initChooseUserData };
        })();
        WebAPP.initChooseUserData();
    </script>
</body>
</html>