RayelinkWeixin.Web/Areas/ReVisit/Models/Doctor.cs
using Newtonsoft.Json;

namespace RayelinkWeixin.Web.Areas.ReVisit.Models
{
    /// <summary>
    /// 接口返回的医生对象信息
    /// </summary>
    public class Doctor
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("pointDiagnosis")]
        public int PointDiagnosis { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("stampUrl")]
        public string StampUrl { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("deptName")]
        public string DeptName { get; set; }

        [JsonProperty("depName2")]
        public string DepName2 { get; set; }

        [JsonProperty("titleName")]
        public string TitleName { get; set; }

        [JsonProperty("orgName")]
        public string OrgName { get; set; }

        [JsonProperty("affiliatedHospital")]
        public string AffiliatedHospital { get; set; }

        [JsonProperty("skillIn")]
        public string SkillIn { get; set; }

        [JsonProperty("comments")]
        public int Comments { get; set; }

        [JsonProperty("consultations")]
        public int Consultations { get; set; }

        [JsonProperty("prizes")]
        public int Prizes { get; set; }

        [JsonProperty("messages")]
        public int Messages { get; set; }

        [JsonProperty("rating")]
        public int[] Rating { get; set; }

        [JsonProperty("remark")]
        public string Remark { get; set; }
    }
}

RayelinkWeixin.Web/Areas/ReVisit/Controllers/DoctorController.cs
using Newtonsoft.Json;
using RayelinkWeixin.Business;
using RayelinkWeixin.Common.Utilites;
using RayelinkWeixin.Const.Const;
using RayelinkWeixin.DLL;
using RayelinkWeixin.Web.Filters;
using Senparc.Weixin.MP.AdvancedAPIs.OAuth;
using System;
using System.Reflection;
using System.Web.Mvc;

namespace RayelinkWeixin.Web.Controllers
{
    /// <summary>
    /// 医生
    /// </summary>
    public partial class ReVisitController
    {

        #region 医生列表
        /// <summary>
        /// 医生列表
        /// </summary>
        /// <returns></returns>
        [WxOAuthAuthorize("super", appid: KeyConst.OrderAppId)]
        public ActionResult DoctorIndex(string openid)
        {
            ReVisitLoyout(ref openid);
            var user = ReVisitBusiness.Instance.GetUserCacheByOpenId(openid);   //当前用户信息
            if (null != user && (user.UserType == KeyConst.ReVisit_UserType_Assistant || user.UserType == KeyConst.ReVisit_UserType_Doctor))
            {
                return Content("医生/助理无权限进入此页面，请退出页面......");
            }
            ViewBag.Doctors = ReVisitBusiness.Instance.DoctorsInfo;
            InitUser(openid);   // 初始化一个用户信息
            return View(string.Format(ViewPath, RouteData.Values["action"]));
        } 
        #endregion

        #region 初始化一个用户信息
        /// <summary>
        /// 初始化一个用户信息
        /// </summary>
        /// <param name="openid"></param>
        private void InitUser(string openid)
        {
            try
            {
                var userInfo = ReVisitBusiness.Instance.GetUserCacheByOpenId(openid, KeyConst.ReVisit_UserType_User);   //当前用户信息
                string nickname = string.Empty;
                string avatarUrl = string.Empty;
                if (null != this.Request.QueryString["userinfo"])
                {
                    OAuthUserInfo oAuthUserinfo = JsonConvert.DeserializeObject<OAuthUserInfo>(Request.QueryString["userinfo"]);  //高级授权获取的用户详细信息
                    if (null != oAuthUserinfo)
                    {
                        nickname = oAuthUserinfo.nickname;
                        avatarUrl = oAuthUserinfo.headimgurl;
                    }
                }
                if (null == userInfo)
                {
                    if (!string.IsNullOrWhiteSpace(nickname) && !string.IsNullOrWhiteSpace(avatarUrl))
                    {
                        BusinessContent.FZ_User.Insert(new Model.FZ_UserInfo { OpenId = openid, UserType = KeyConst.ReVisit_UserType_User, Status = 1, NickName = nickname, AvatarUrl = avatarUrl });
                    }
                    else
                    {
                        BusinessContent.FZ_User.Insert(new Model.FZ_UserInfo { OpenId = openid, UserType = KeyConst.ReVisit_UserType_User, Status = 1 });
                    }                   
                }
                else if (!string.IsNullOrWhiteSpace(nickname) && !string.IsNullOrWhiteSpace(avatarUrl))
                {                   
                    BusinessContent.FZ_User.Update(new { NickName = nickname, AvatarUrl = avatarUrl }, userInfo.Id);//修改头像

                    ReVisitBusiness.Instance.ClearUserCacheByOpenId(openid, userInfo.UserType);  // 清空一条用户信息缓存
                }
            }
            catch (Exception ex)
            {
                LogHelper.Exception(ex);
            }
        }
        #endregion

        #region 刷新一个医生的缓存信息
        /// <summary>
        /// 刷新一个医生的缓存信息
        /// </summary>
        /// <param name="orderSid"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult FlushDortor(string doctorOpenid)
        {
            Common.Share.ReturnMessage rm = new Common.Share.ReturnMessage { Text = "操作完成" };
            try
            {
                rm.IsSuccess = true;
                ReVisitBusiness.Instance.ClearUserCacheByOpenId(doctorOpenid, KeyConst.ReVisit_UserType_Doctor);  //清空一条用户信息缓存      
            }
            catch (Exception ex)
            {
                rm.IsSuccess = false;
                rm.Text = "操作出错";
                rm.Message = ex.Message;
                var declaringType = MethodBase.GetCurrentMethod().DeclaringType;
                if (declaringType != null) { ex.Data["Method"] = declaringType.Name + "=>" + MethodBase.GetCurrentMethod().Name; }
                LogHelper.Exception(ex);
            }
            return MyJson(rm, JsonRequestBehavior.AllowGet);
        }
        #endregion

    }
}

RayelinkWeixin.Web/Controllers/DoctorController.cs
/*----------------------------------------------------------------
// Copyright (C) 2016苏州盈天地资讯科技公司
// 版权所有。
// 文   件   名：DoctorController
// 文件功能描述：
//
// 
// 创 建 人：haiqing
// 创建日期：2016-01-21
//
// 修 改 人：
// 修改描述：
//
// 修改标识：
//----------------------------------------------------------------*/

using Newtonsoft.Json;
using RayelinkWeixin.Common.Utilites;
using RayelinkWeixin.Const.Config;
using RayelinkWeixin.Const.Const;
using RayelinkWeixin.Model;
using RayelinkWeixin.Web.Filters;
using RayelinkWeixin.Web.Models;
using Senparc.Weixin.MP.Containers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using RayelinkWeixin.Web.Controllers;

namespace RayelinkWeixin.Web.Areas.ReVisit.Controllers
{
    [AllowAnonymous]
    public class DoctorController : BaseController
    {
        /// <summary>
        /// 进入专家列表页面
        /// </summary>
        /// <returns></returns>
        [WeixinSpeficAuthorize]
        public ActionResult DoctorList()
        {

            var url = Request.Url.ToString().Split('#')[0];
            ViewBag.JsSDKModel = JsSDKModel.GetJsSDKModel(url);
            // 科室  职称列表（带缓存）
            var objDept = CacheHelper.GetCache(KeyConst.CacheAllDept);
            var objTitle = CacheHelper.GetCache(KeyConst.CacheAllTitle);
            var listDepartment = new List<SelectItemModel>();
            var listTitle = new List<SelectItemModel>();
            CRSService.CRS_ServiceSoapClient client = new CRSService.CRS_ServiceSoapClient();
            // 判断缓存是否有
            if (objDept != null)
            {
                listDepartment = objDept as List<SelectItemModel>;
            }
            else
            {
                listDepartment.Add(new SelectItemModel()
                {
                    id = "",
                    name = "全部"
                });

                var returnModel = client.getDeptList();
                var deptJson = returnModel.Data.ToString();
                var deptList = JsonConvert.DeserializeObject<List<SelectItemModel>>(deptJson).OrderBy(p => p.name).ToList();
                foreach (SelectItemModel obj in deptList)
                {
                    obj.name = obj.name.Length > 8 ? obj.name.Substring(0, 8) + "..." : obj.name;
                }
                listDepartment.AddRange(deptList.ToArray());
                if (listDepartment.Count > 0)
                {
                    CacheHelper.SetCache(KeyConst.CacheAllDept, listDepartment);
                }
            }
            // 判断缓存是否有
            if (objTitle != null)
            {
                listTitle = objTitle as List<SelectItemModel>;
            }
            else
            {
                listTitle.Add(new SelectItemModel()
                {
                    id = "",
                    name = "全部"
                });
                var returnModel1 = client.getTitleList();
                var titleJson = returnModel1.Data.ToString();
                var titleList = JsonConvert.DeserializeObject<List<SelectItemModel>>(titleJson);
                listTitle.AddRange(titleList.ToArray());
                if (listTitle.Count > 0)
                {
                    CacheHelper.SetCache(KeyConst.CacheAllTitle, listTitle);
                }
            }
            ViewBag.Department = listDepartment;
            ViewBag.Title = listTitle;
            return View();
        }

        /// <summary>
        /// 获取专家列表数据
        /// </summary>
        /// <param name="deptid">部门</param>
        /// <param name="titleid">职称</param>
        /// <param name="keyword">关键字</param>
        /// <param name="currentIndex">当前页</param>
        /// <param name="page">页数</param>
        /// <returns></returns>
        public ActionResult GetDoctorList(int? deptid, int? titleid, string keyword, int currentIndex, int page = 10)
        {
            CRSService.CRS_ServiceSoapClient client = new CRSService.CRS_ServiceSoapClient();
            var returnModel = client.getDoctorList(deptid, titleid, keyword,"","1,2,3","", currentIndex, page);
            var doctorListJson = "";
            if (returnModel.Data != null)
            {
                doctorListJson = returnModel.Data.ToString();
            }
            if (doctorListJson == "")
            {
                doctorListJson = "[]"; //防止前台jquery ajax报parseerror 错误
            }
            return Content(doctorListJson);


        }

        /// <summary>
        /// 搜索页
        /// </summary>
        /// <returns></returns>
        [WeixinSpeficAuthorize]
        public ActionResult DoctorSearch()
        {
            var url = Request.Url.ToString().Split('#')[0];
            ViewBag.JsSDKModel = JsSDKModel.GetJsSDKModel(url);
            return View();
        }

        /// <summary>
        /// 搜索空白页
        /// </summary>
        /// <param name="searchText"></param>
        /// <returns></returns>
        [WeixinSpeficAuthorize]
        public ActionResult DoctorSearchNull(string searchText)
        {
            var url = Request.Url.ToString().Split('#')[0];
            ViewBag.JsSDKModel = JsSDKModel.GetJsSDKModel(url);
            ViewBag.searchText = searchText;
            return View();
        }

        /// <summary>
        /// 医生详情页
        /// </summary>
        /// <param name="id">医生id</param>
        /// <param name="date">日期</param>
        /// <param name="isPrize">定位送心意</param>
        /// <returns></returns>
        [WeixinSpeficAuthorize]
        public ActionResult DoctorSub(int id, string date = "", int isPrize =0)
        {
            var url = Request.Url.ToString().Split('#')[0];
            ViewBag.JsSDKModel = JsSDKModel.GetJsSDKModel(url);
            ViewBag.isPrize = isPrize;
            CRSService.CRS_ServiceSoapClient client = new CRSService.CRS_ServiceSoapClient();
            DoctorModel doctorModel = new DoctorModel();
            var returnModel5 = client.getDoctor(id);
            // 获得医生详细数据
            var doctorJson = "";
            if (returnModel5.Data != null)
            {
                doctorJson = returnModel5.Data.ToString();
                if (doctorJson != "")
                {
                    doctorModel = JsonConvert.DeserializeObject<DoctorModel>(doctorJson);
                }
            }


            if (User.Identity.IsAuthenticated)
            {
                var user = AuthorizeUser.GetAuthorizeUser(User.Identity.Name);
                if (user != null)
                {
                    // 是否关注医生
                    var returnModel = client.isAttention(user.pid, id);
                    var attentionJson = "0";
                    if (returnModel.Data != null)
                    {
                        attentionJson = returnModel.Data.ToString();
                    }
                    if ("0".Equals(attentionJson))
                    {
                        doctorModel.isFocus = false;
                    }
                    else
                    {
                        doctorModel.isFocus = true;
                    }
                    doctorModel.isLogin = true;
                    doctorModel.userName = user.username;
                }
            }
            else
            {
                doctorModel.isFocus = false;
                doctorModel.isLogin = false;
                doctorModel.userName = AuthorizeUser.nickname();
            }
            #region 医生信息 应该从接口获取

            var pid = 0;
            if (User.Identity.IsAuthenticated)
            {
                var user = AuthorizeUser.GetAuthorizeUser(User.Identity.Name);
                if (user != null)
                {
                    pid = user.pid;
                }
            }

            #region 我的咨询
            var returnModel6 = client.GetLatestUserConsultations(id, pid);
            var latestUserMessageJson = "";
            if (returnModel6.Data != null)
            {
                latestUserMessageJson = returnModel6.Data.ToString();
            }
            doctorModel.currentLatestConsult = new OnlineConsultModel();
            if (latestUserMessageJson != "")
            {
                var latestUserMessageModel = JsonConvert.DeserializeObject<OnlineConsultModel>(latestUserMessageJson);

                if (latestUserMessageModel != null)
                {
                    doctorModel.currentLatestConsult = latestUserMessageModel;
                    doctorModel.currentLatestConsult.CreateTime = Convert.ToDateTime(doctorModel.currentLatestConsult.CreateTime).ToString("yyyy.MM.dd");
                    doctorModel.currentLatestConsult.Content = doctorModel.currentLatestConsult.Content;
                }
            }
            
            // 其他咨询
            var returnModel7 = client.GetTopUserConsultations(id, pid, 4);
            var userMessageListJson = returnModel7.Data.ToString();
            var userMessageListModel = JsonConvert.DeserializeObject<List<OnlineConsultModel>>(userMessageListJson);
            if (userMessageListModel != null)
            {
                foreach (var OnlineConsultModel in userMessageListModel)
                {
                    OnlineConsultModel.CreateTime = Convert.ToDateTime(OnlineConsultModel.CreateTime).ToString("yyyy.MM.dd");
                    OnlineConsultModel.UserName = OnlineConsultModel.UserName.Substring(0, 1) + "**";
                    OnlineConsultModel.Content = OnlineConsultModel.Content;
                }
            }

            doctorModel.listConsult = new List<OnlineConsultModel>();
            if (userMessageListModel != null)
            {
                doctorModel.listConsult.AddRange(userMessageListModel.ToArray());
            }
            #endregion

            #region 评论
            doctorModel.listUserComments = new List<UserCommentModel>();
            var returnModel2 = client.getCommentList(id, null, pid, 1, 5);

RayelinkWeixin.Web/Views/Doctor/DoctorSearch.cshtml
@{
    Layout = null;
    var jsSDKModel = ViewBag.JsSDKModel as RayelinkWeixin.Web.Models.JsSDKModel;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>专家列表</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta http-equiv="cleartype" content="on">
    <meta name="format-detection" content="telephone=no" />
    <link rel="stylesheet" href="../styles/base.css?v=2">
    <link rel="stylesheet" href="../styles/doctor_search.css">
    <script src="../vendor/jquery-2.1.0.min.js"></script>
    <script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
    <script>
        wx.config({
            debug: false,
            appId: '@jsSDKModel.appId',
            timestamp: '@jsSDKModel.timestamp',
            nonceStr: '@jsSDKModel.nonceStr',
            signature: '@jsSDKModel.signature',
            jsApiList: ['hideAllNonBaseMenuItem']
        });
        wx.ready(function () {
            wx.hideAllNonBaseMenuItem();
        });
    </script>

    <style type="text/css">
        #search_btn {
            width: 80%;
        }
    </style>
</head>
<body>
    <section class="wrap">
        <nav class="search_wrap">
            <section>
                <form>
                    <input type="text" id="search_btn" placeholder="请输入医生姓名/疾病名称" onkeyup="showDelete_Icon()" oninput="showDelete_Icon()">
                    <i class="delIcon" style="display:none;left:75%;" id="showIcon"></i>
                    <a href="javascript:;" class="clean_btn">取消</a>
                </form>
            </section>
        </nav>
        <section class="search_storage">
            <p class="storage_label">
                <label>搜索历史</label>
            </p>
            <ul class="local_storage"></ul>
            <a href="#" class="storage_clear"><span>清除搜索历史</span></a>
        </section>
        <section class="no_item shadow"></section>
    </section>
    <script id="tmplHistory" type="text/x-jsrender">
        <li><span>{{:#data}}</span></li>
    </script>
    <script src="../vendor/jsrender.min.js"></script>
    <script type="text/javascript">
        $(function () {
            var str = window.localStorage.getItem('SearchHistory');
            if (str == null || str == '') {
                $('.storage_label').hide();
                $('.storage_clear').hide();
            }

            var WebAPP = (function () {
                var utils = {
                    search: function (searchText) {
                        var str = window.localStorage.getItem('SearchHistory');
                        if (str == null || str == '') {
                            window.localStorage.setItem('SearchHistory', JSON.stringify([searchText]));
                            window.sessionStorage.setItem('searchText', searchText)
                            window.location.href = '@Url.Action("DoctorList","Doctor")' + "?Random=" + Math.random();
                        } else {
                            var dataJson = JSON.parse(str);
                            var indexOf = dataJson.indexOf(searchText);
                            if (indexOf >= 0) {
                                dataJson.splice(indexOf, 1);
                            }
                            dataJson.unshift(searchText);
                            window.localStorage.setItem('SearchHistory', JSON.stringify(dataJson));
                            window.sessionStorage.setItem('searchText', searchText);
                            window.location.href = '@Url.Action("DoctorList","Doctor")' + "?Random=" + Math.random();
                        }
                    }
                };
                var initHistory = function () {
                    var str = window.localStorage.getItem('SearchHistory');
                    if (str != null && str != '') {
                        var dataJson = JSON.parse(str);
                        $('.storage_label').show();
                        $('.storage_clear').show();
                        var topSixString = "";
                        for (i = 0; i < dataJson.length; i++) {
                            var subSearchText = dataJson[i];
                            if (i < 6) {
                                if (subSearchText.length > 20) {
                                    subSearchText = subSearchText.substring(0, 20) + "...";
                                }
                                topSixString += "\"" + subSearchText + "\","
                            }
                        }
                        topSixString = "[" + topSixString.substring(0, topSixString.length - 1) + "]";
                        var topSixJson = JSON.parse(topSixString);
                        $(".local_storage").empty().html($("#tmplHistory").render(topSixJson));
                    } else {
                        $(".local_storage").empty().html($("#tmplHistory").render([]));
                    }
                };
                var chearHistory = function () {
                    $('.storage_clear').on('click touchstart touchend', function (e) {
                        e.preventDefault();
                        window.localStorage.removeItem('SearchHistory');
                        $('.storage_label').hide();
                        $('.storage_clear').hide();
                        initHistory();
                    });
                };
                var clearSearchText = function () {
                    $('.clean_btn').on('click', function (e) {
                        e.preventDefault();
                            window.location.href = '/Doctor/DoctorList';
                    });
                };
                var search = function () {
                    $('#search_btn').on('keydown', function (e) {
                        if (e.which == '13') {
                            var searchText = $.trim($('#search_btn').val());
                            if (searchText == '') {
                                return false;
                            } else {
                                e.preventDefault();
                                utils.search(searchText);
                            }
                        }
                    });
                };
                var chooseHistoryItem = function () {
                    $('.local_storage').find('li').on('click', function (e) {
                        e.preventDefault();
                        var index = $(this).prevAll().length;
                        var str = window.localStorage.getItem('SearchHistory');
                        var dataJson = JSON.parse(str);
                        var searchText = dataJson[index];
                        utils.search(searchText);
                    });
                };
                return {
                    InitHistory: initHistory,
                    ChearHistory: chearHistory,
                    ClearSearchText: clearSearchText,
                    Search: search,
                    ChooseHistoryItem: chooseHistoryItem
                };
            })();
            WebAPP.InitHistory();
            WebAPP.ChearHistory();
            WebAPP.ClearSearchText();
            WebAPP.ChooseHistoryItem();
            WebAPP.Search();

            $(".delIcon").on('click touchstart touchend', function (e) {
                $('#search_btn').val("");
                $("#showIcon").hide();
            });
        });
        function showDelete_Icon() {
            var value = $("#search_btn").val();
            var len = value.length;
            if (len>0) {
                $("#showIcon").show();
            }
            else {
                $("#showIcon").hide();
            }
        }
        showDelete_Icon();
    </script>
    <script src="../scripts/doctor_search.js"></script>
</body>
</html>

RayelinkWeixin.Web/Views/Doctor/SendPrize.cshtml
@{
    Layout = null;
    var placeholder = "请表达您对" + Model.name + "医生的感谢";
    var jsSDKModel = ViewBag.JsSDKModel as RayelinkWeixin.Web.Models.JsSDKModel;
}
@model DoctorModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>送心意</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta http-equiv="cleartype" content="on">
    <meta name="format-detection" content="telephone=no" />
    <link rel="stylesheet" href="../styles/base.css?v=2">
    <link rel="stylesheet" href="../styles/send_prize.css">
    <script src="../vendor/jquery-2.1.0.min.js"></script>
    <script src="../scripts/base.js?v=2"></script>
    <script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
    <script>
        wx.config({
            debug: false,
            appId: '@jsSDKModel.appId',
            timestamp: '@jsSDKModel.timestamp',
            nonceStr: '@jsSDKModel.nonceStr',
            signature: '@jsSDKModel.signature',
            jsApiList: ['hideAllNonBaseMenuItem']
        });
        wx.ready(function () {
            wx.hideAllNonBaseMenuItem();
        });
    </script>
    <style>
        .doctor_name{margin-right:0;}
        .doctor_skills{width:auto;max-width:170px;}
    </style>
</head>
<body>
    <section class="wrap">
        <div class="doctor_info">
            @if (Model.image != "")
            {
                <span class="doctor_icon"><img src="@Model.image"></span>
            }
            else
            {
                <span class="doctor_icon"><img src="../images/default.png"></span>
            }

            <span class="doctor_name">@Model.name</span>
            <span class="doctor_skills">【@Model.deptName-@Model.titleName 】</span>
        </div>
        <div class="comments">
            <div class="wrap">
                <p>感谢ta，就为ta送上一面锦旗吧！</p>
                <ul>
                    <li data-level="1" class="flag1 flags"><img src="../images/send_prize/flag1.png" alt="#"><span class="shadow">10元</span></li>
                    <li data-level="2" class="flag2 flags"><img src="../images/send_prize/flag2.png" alt="#"><span class="shadow">5元</span></li>
                    <li data-level="3" class="flag3 flags"><img src="../images/send_prize/flag3.png" alt="#"><span class="shadow">1元</span></li>
                </ul>
            </div>
            <div class="messages">
                <textarea name="messages" id="messages" rows="8" placeholder="@placeholder" required="required"></textarea>
            </div>
        </div>
    </section>
    <a href="javascript:void(0);" class="goCheck">立即支付</a>
    <input type="hidden" id="hidLevel" value="0" />
    <script src="../scripts/send_prize.js"></script>
    <script type="text/javascript">
      
        $(function () {
            var sesslevel = window.sessionStorage.getItem("sesslevel");
            var sesscontent = window.sessionStorage.getItem("sesscontent");
            if (sesslevel != "" && sesslevel != null)
            {
                $('#hidLevel').val(sesslevel);
                var le = $(".flags[data-level=" + sesslevel + "]");
                le.addClass('active').find('span').removeClass('shadow');
                window.sessionStorage.removeItem("sesslevel")
            }

            if (sesscontent != "" && sesscontent != null) {
                $('#messages').val(sesscontent);
                window.sessionStorage.removeItem("sesscontent")
            }
            $('.goCheck').on('click', function () {
                var level = $('#hidLevel').val();
                var docID = '@Model.id';
                var openid = $('#hidStorageOpenID').val();
                var conetnt = $.trim($('#messages').val());
                if (conetnt.length > 200) {
                    base.caozuotishi(2, '最多输入200个字符');
                    return false;
                }
                if (base.is_emoji(conetnt)) {
                    base.caozuotishi(2, '无法输入表情');
                    return false;
                }
                if (level == 0) {
                    base.caozuotishi(2, "请选择一面锦旗！");
                    return true;
                }

                var loading = $('<div class="loading"><figure class="load_img"><img src="../images/loading.gif" alt="" style="width:32px;height:32px;"></figure></div>');
                $(".wrap").append(loading);
                var ajaxPost = $.ajax({
                    url: '@Url.Action("goToPay", "Doctor")',
                    type: "POST",
                    data: {
                        docID: docID, level: level, content: conetnt, openid: openid
                    },
                    timeout: 15000,
                    dataType: "json",
                    success: function (data) {
                        $(".loading").remove();
                        var success = data.success;
                        var orderNo = data.data;
                        var amount = data.amount;
                        if (success) {
                            window.sessionStorage.setItem("sesslevel", level);
                            window.sessionStorage.setItem("sesscontent", conetnt);
                            window.location.href = '@Url.Action("Index","WeixinPay")' + '?orderNo=' + orderNo + '&amount=' + amount + '&docID=' + docID+"&type=0";
                        } else {
                            base.caozuotishi(2, '发起支付异常');

                        }
                    },
                    error: function (e) {
                        if ($(".loading") != null && $(".loading").length > 0) {
                            $(".loading").remove();
                        }
                    },
                    complete: function (XMLHttpRequest, status) { //请求完成后最终执行参数
                        if (status == 'timeout') {//超时,status还有success,error等值的情况
                            ajaxPost.abort();
                            if ($(".loading") != null && $(".loading").length > 0) {
                                $(".loading").remove();
                            }
                            $(".wrap").empty().append("<section class='no_loading'></section>");
                        }
                        if (status == "error") {
                            base.caozuotishi(2, "数据加载失败，请检查网络后重试");
                            if ($("figure.no_success_box img") != null && $("figure.no_success_box img").length > 0) {
                                $("figure.no_success_box img").hide();
                            }
                        }
                    }
                });

            });
        });

    </script>
</body>
</html>